### ISSUE TITLE
ip protocol

### ISSUE THREAD

**Issue by mgaulton** [mrash/fwsnort#10]
Interestingly, -p ip was invalid on my system so i replaced it with -p all
referred to this http://ipset.netfilter.org/iptables.man.html

iptables v1.4.21: no command specified
Opensuse 13.2

cd /var/lib/fwsnort
fwsnort
sed -i "s/-p ip/-p all/g" fwsnort_iptcmds.sh
./fwsnort_iptcmds.sh

**Comment by mrash** [comment]
FIxed, thanks.
