### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by ghost** [mrash/fwsnort#16]
Michael:

Hey it's been super depressing coming across these poor abandoned Linux Security repos from the last few years.

I'm a weird situation now where I can just use IPTables essentially, so finding this produced the greatest joy Github has ever given me.

Thanks not only for working on this, but continuing for what seems like a decade+.

YOU ARE GREAT 

- Dan Ehrlich

**Comment by mrash** [comment]
Thanks, I appreciate the sentiment. Working on an issue for the next release of fwsnort.
