### ISSUE TITLE
ifconfig not present

### ISSUE THREAD

**Issue by mgaulton** [mrash/fwsnort#9]
On my opensuse 13.2 system, i don't have ifconfig and there's no package i can find to install so I use ip add, any suggestions on how to tweak this to make it work with that instead?

**Comment by mgaulton** [comment]
I had to install a package called net-tools-deprecated. thanks.

**Comment by mrash** [comment]
Thanks for the report. I'll update fwsnort to use the ip command when it is available instead of ifconfig. 'ip addr show' gives the same information that ifconfig is used for by fwsnort.

**Comment by mgaulton** [comment]
No worries
